CREATE TYPE "BillStatus" AS ENUM ('PENDING', 'PAID', 'OVERDUE', 'SKIPPED');
CREATE TYPE "BillPriority" AS ENUM ('ESSENTIAL', 'FLEXIBLE');

ALTER TABLE "bills"
ADD COLUMN "estimatedAmount" DECIMAL(65,30),
ADD COLUMN "lastPaidAmount" DECIMAL(65,30),
ADD COLUMN "paidAmount" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "status" "BillStatus" NOT NULL DEFAULT 'PENDING',
ADD COLUMN "category" TEXT,
ADD COLUMN "priority" "BillPriority" NOT NULL DEFAULT 'ESSENTIAL',
ADD COLUMN "isAutoPay" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "isVariableAmount" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "reminderDays" INTEGER[] NOT NULL DEFAULT ARRAY[7,3,1,0]::INTEGER[],
ADD COLUMN "sentReminderOffsets" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN "lastOverdueReminderSent" TIMESTAMP(3),
ADD COLUMN "paidAt" TIMESTAMP(3),
ADD COLUMN "paymentProof" TEXT,
ADD COLUMN "notes" TEXT,
ADD COLUMN "sharedWith" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "splitConfig" JSONB,
ADD COLUMN "paymentHistory" JSONB,
ADD COLUMN "missedPaymentCount" INTEGER NOT NULL DEFAULT 0;
